### ISSUE TITLE
convert_lpgs_to_espa - failed to load external entity

### ISSUE THREAD

**Issue by pesekon2** [USGS-EROS/espa-surface-reflectance#106]
I just installed `lasrc` and when I try to run `convert_lpgs_to_espa --mtl path_to_MTL.txt_file`, I always end up in this error. Is there any problem with my installation? 

```
error : Unknown IO error
I/O warning : failed to load external entity "http://espa.cr.usgs.gov/schema/espa_internal_metadata_v2_2.xsd"
Schemas parser error : Failed to locate the main schema resource at 'http://espa.cr.usgs.gov/schema/espa_internal_metadata_v2_2.xsd'.
error : Unknown IO error
I/O warning : failed to load external entity "http://espa.cr.usgs.gov/schema/espa_internal_metadata_v2_2.xsd"
/opt/qcmms/test_data/LC08_L1TP_192026_20150419_20170409_01_T1/LC08_L1TP_192026_20150419_20170409_01_T1.xml:6: element espa_metadata: Schemas validity warning : Element '{http://espa.cr.usgs.gov/v2}espa_metadata', attribute '{http://www.w3.org/2001/XMLSchema-instance}schemaLocation': The document at location 'http://espa.cr.usgs.gov/schema/espa_internal_metadata_v2_2.xsd' could not be acquired.
/opt/qcmms/test_data/LC08_L1TP_192026_20150419_20170409_01_T1/LC08_L1TP_192026_20150419_20170409_01_T1.xml:6: element espa_metadata: Schemas validity error : Element '{http://espa.cr.usgs.gov/v2}espa_metadata': No matching global declaration available for the validation root.
Error: validate_xml_file : /opt/qcmms/test_data/LC08_L1TP_192026_20150419_20170409_01_T1/LC08_L1TP_192026_20150419_20170409_01_T1.xml fails to validate
```

When I try to download `http://espa.cr.usgs.gov/schema/espa_internal_metadata_v2_2.xsd` with `wget`, it works. Working with releases `product_formatter_v1.19.0`, `lasrc_v2.0.0`.

**Comment by gschmidt-usgs** [comment]
This issue belongs to espa-product-formatter, not espa-surface-reflectance.
Did you set the ESPA_SCHEMA location in your bashrc or tcshsrc file to point to the location of the schema on your local system?
setenv ESPA_SCHEMA {$PREFIX}/schema/espa_internal_metadata_v2_2.xsd

For further questions, please note this information in the README.
This project is unsupported software provided by the U.S. Geological Survey (USGS) Earth Resources Observation and Science (EROS) Land Satellite Data Systems (LSDS) Project. For questions regarding products produced by this source code, please contact us at custserv@usgs.gov.

**Comment by pesekon2** [comment]
Oh, true, it was for `espa-product-formatter`, I just discovered it while testing the installation of this. Sorry, my fault. 

However, your advise helped. I did not set the `ESPA_SCHEMA` (actually, I did not find any info saying that I should do it). Setting it fixes the problem.
