### ISSUE TITLE
process_sr argument does not act as expected

### ISSUE THREAD

**Issue by NGenetzky** [USGS-EROS/espa-surface-reflectance#29]
C executable, l8_sr will request that process_sr=false for an OLI-only scene; however do_l8_sr.py reads the string "false" as True. It does parse "False" correctly.

"Error: main : This is an OLI-only scene vs. an OLI-TIRS scene. Corrections must be limited to top of atmosphere and at-sensor brightness temperature corrections. Use the --process_sr=false command-line argument to process. (oli-only cannot be corrected to surface reflectance)"

This can be solved by the script wrapper.

**Comment by gschmidt-usgs** [comment]
This does work correctly.  The default is to process surface reflectance
unless process_sr is set to False for the Python script.  Python uses True
and False.  The C executable uses true and false.

--------------------------------------------------------------
Gail Schmidt
Software Engineer
Stinger Ghaffarian Technologies (SGT, Inc.)
Contractor to the USGS Earth Resources Observation and Science (EROS) Center
Rapid City, SD  57701
605-593-2722   Phone
605-394-6078   Fax
gschmidt@usgs.gov

Adaptation - "Manage the unavoidable"
Mitigation - "Avoid the unmanageable"

**Comment by NGenetzky** [comment]
Ok. I guess I was just sharing my point of view as an end user. I think the default parameter should be used when the argument is not specified but not when an invalid argument in specified. All three statements below are the same and I think it is error prone.
```
do_l8_sr.py --xml LC80470272013287LGN00.xml --process_sr=notaboolean
do_l8_sr.py --xml LC80470272013287LGN00.xml --process_sr=false
do_l8_sr.py --xml LC80470272013287LGN00.xml
```

**Comment by gschmidt-usgs** [comment]
You are correct.  It could always be enhanced.  Not opposed to that.

--------------------------------------------------------------
Gail Schmidt
Software Engineer
Stinger Ghaffarian Technologies (SGT, Inc.)
Contractor to the USGS Earth Resources Observation and Science (EROS) Center
Rapid City, SD  57701
605-593-2722   Phone
605-394-6078   Fax
gschmidt@usgs.gov

Adaptation - "Manage the unavoidable"
Mitigation - "Avoid the unmanageable"
