### ISSUE TITLE
Add per-pixel Julian date/year bands

### ISSUE THREAD

**Issue by sfoga-usgs** [USGS-EROS/espa-surface-reflectance#33]
Adding a Julian date and year band(s) would be helpful for downstream compositing applications. Possible implementation of this feature:

A) Applying to a single UINT32 band as "2015232" for August 20, 2015.
B) Apply year to a UINT16 band, and Julian date to another UINT16 band.

The Julian date/year can easily be copied from the Landsat sceneID.

**Comment by gschmidt-usgs** [comment]
This will actually be a separate library/tool in the espa-product-formatter
that creates the Julian date/year band.  There is no need to make this part
of the surface reflectance corrections.  I will move the request to that
Github project.

--------------------------------------------------------------
Gail Schmidt
Software Engineer
Stinger Ghaffarian Technologies (SGT, Inc.)
Contractor to the USGS Earth Resources Observation and Science (EROS) Center
Rapid City, SD  57701
605-593-2722   Phone
605-394-6078   Fax
gschmidt@usgs.gov

Adaptation - "Manage the unavoidable"
Mitigation - "Avoid the unmanageable"

**Comment by gschmidt-usgs** [comment]
This request has been pushed over to espa-product-formatter for stand-alone implementation.
