### ISSUE TITLE
link to auxilliary files is broken

### ISSUE THREAD

**Issue by JanMil** [USGS-EROS/espa-surface-reflectance#48]
Following the given link for the auxilliary data (http://espa.cr.usgs.gov/downloads/auxiliaries/l8sr_auxiliary/l8sr_auxiliary.tar.gz) is not working. 

404 Not Found
The requested URL /lsrd/downloads/auxiliaries/l8sr_auxiliary/l8sr_auxiliary.tar.gz was not found on this server.

**Comment by dhill-usgs** [comment]
The file has been replaced.

On Tue, Nov 17, 2015 at 8:13 AM, Jan Militzer <notifications@github.com>
wrote:

> Following the given link for the auxilliary data (
> http://espa.cr.usgs.gov/downloads/auxiliaries/l8sr_auxiliary/l8sr_auxiliary.tar.gz)
> is not working.
>
> 404 Not Found
> The requested URL
> /lsrd/downloads/auxiliaries/l8sr_auxiliary/l8sr_auxiliary.tar.gz was not
> found on this server.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/USGS-EROS/espa-surface-reflectance/issues/48>.
>



-- 
David V. Hill
LSRD
SGT
Contractor to USGS Earth Resources Observation And Science Center (EROS)
47914 252nd Street
Sioux Falls, SD 57198-9801
605.594.2639
dhill@usgs.gov

**Comment by yannforget** [comment]
The link seems broken again.

**Comment by stevefoga** [comment]
Yann, the storage system is down for maintenance this morning, as indicated on the ESPA homepage.

**Comment by safalabolo** [comment]
tomorrow it could be available ...

**Comment by yannforget** [comment]
My apologies! Thanks for the fast response.

**Comment by safalabolo** [comment]
Dear Yann,dear Steve
Thanks for Your support!
All the best!!
