### ISSUE TITLE
Auxilary data link down...

### ISSUE THREAD

**Issue by meerestier** [USGS-EROS/espa-surface-reflectance#67]
http://espa.cr.usgs.gov/downloads/auxiliaries/ledaps_auxiliary/ledaps_aux.1978-2014.tar.gz

This link is not working. Could somebody update the readme and/or provide a working link?

Best regards 
Lars

**Comment by gschmidt-usgs** [comment]
The link has been updated and should work now.  Thanks.

-----------------------------------------------------------------------------------------------------
Gail Schmidt
Software Engineer
Stinger Ghaffarian Technologies (SGT)
Contractor to the U.S. Geological Survey (USGS)
Earth Resources Observation and Science (EROS) Center
47914 252nd Street
Sioux Falls, SD 57198
Phone: 605-593-2272
gail.schmidt.ctr@usgs.gov

NOTICE:  This email may contain confidential, proprietary, or competition
sensitive bid or proposal procurement information.  Unauthorized disclosure
of this information may carry criminal penalties as set forth in the
Procurement Integrity Act, 41 U.S.C. 423, as amended.  Further, the
unauthorized disclosure of certain commercial information by civil servants
may result in fines or imprisonment under the Trade Secrets Act (18 U.S.C.
1905).  If you have received this information in error, please delete it,
including all copies, and notify the sender of the error immediately.

**Comment by meerestier** [comment]
Thank you for taking care of it so quickly…

For tidiness, I state the link here as well. http://edclpdsftp.cr.usgs.gov/downloads/auxiliaries/ledaps_auxiliary/ledaps_aux.1978-2014.tar.gz
