### ISSUE TITLE
building ledapsAncSrc

### ISSUE THREAD

**Issue by daveoloughlin** [USGS-EROS/espa-surface-reflectance#69]
Can you tell me where to find the crypto library (lcrypto) used to convert_ozone and ncep_repackage? It may not be needed by convert_ozone but ncep_repackage is crashing on me when I build them without this library.

**Comment by caustin-usgs** [comment]
@daveoloughlin its part of the openssl-devel package
rpm -q --whatprovides /usr/lib64/libcrypto.so
openssl-devel-1.0.1e-51.el7_2.7.x86_64

**Comment by daveoloughlin** [comment]
Thanks very much.
