### ISSUE TITLE
Can not read scanlines from a tiled image.

### ISSUE THREAD

**Issue by Leonhalt3141** [USGS-EROS/espa-surface-reflectance#76]
I have built espa-surface-reflectance in Docker environment.  
Based image is `ubuntu:16.04`.
When I run `convert_lpgs_to_espa`, I got `Can not read scanlines from a tiled image.` error and failed to export img files from tif.

I tried to install libtiff and geotiff from both apt-get and source codes, but got same error.
Is there any way to solve this problem?

**Comment by gschmidt-usgs** [comment]
What version of espa-product-formatter are you using?  And which product
are you trying to read?  Can you send the command-line output?

-----------------------------------------------------------------------------------------------------
Gail Schmidt
Software Engineer
Stinger Ghaffarian Technologies (SGT)
Contractor to the U.S. Geological Survey (USGS)
Earth Resources Observation and Science (EROS) Center
47914 252nd Street
Sioux Falls, SD 57198
Phone: 605-594-2527
gail.schmidt.ctr@usgs.gov

NOTICE:  This email may contain confidential, proprietary, or competition
sensitive bid or proposal procurement information.  Unauthorized disclosure
of this information may carry criminal penalties as set forth in the
Procurement Integrity Act, 41 U.S.C. 423, as amended.  Further, the
unauthorized disclosure of certain commercial information by civil servants
may result in fines or imprisonment under the Trade Secrets Act (18 U.S.C.
1905).  If you have received this information in error, please delete it,
including all copies, and notify the sender of the error immediately.

**Comment by Leonhalt3141** [comment]
My version of `espa-product-formatter` is `product_formatter_v1.10.0`.
I have used Level 1 OLI and TIRS combined products.

I run `convert_lpgs_to_espa --mtl LC80430342016092LGN00_MTL.txt`, then got the following standard error.
I got same error by reading other Landsat level 1 scenes.

```
LC80430342016092LGN00_B1.TIF: Can not read scanlines from a tiled image.
LC80430342016092LGN00_B1.TIF: Can not read scanlines from a tiled image.
LC80430342016092LGN00_B1.TIF: Can not read scanlines from a tiled image.
LC80430342016092LGN00_B1.TIF: Can not read scanlines from a tiled image.
...
LC80430342016092LGN00_BQA.TIF: Can not read scanlines from a tiled image.
LC80430342016092LGN00_BQA.TIF: Can not read scanlines from a tiled image.
LC80430342016092LGN00_BQA.TIF: Can not read scanlines from a tiled image.
LC80430342016092LGN00_BQA.TIF: Can not read scanlines from a tiled image.
LC80430342016092LGN00_BQA.TIF: Can not read scanlines from a tiled image.
LC80430342016092LGN00_BQA.TIF: Can not read scanlines from a tiled image.
LC80430342016092LGN00_BQA.TIF: Can not read scanlines from a tiled image.
LC80430342016092LGN00_BQA.TIF: Can not read scanlines from a tiled image.
LC80430342016092LGN00_BQA.TIF: Can not read scanlines from a tiled image.
LC80430342016092LGN00_BQA.TIF: Can not read scanlines from a tiled image.
```

`img` files were exported, but those all values were NULL (real value is 0 and data type is UInt16).

**Comment by gschmidt-usgs** [comment]
Those all look appropriate (except the error messages and failure to read
the scanlines of course).  Let me look at one thing.

-----------------------------------------------------------------------------------------------------
Gail Schmidt
Software Engineer
Stinger Ghaffarian Technologies (SGT)
Contractor to the U.S. Geological Survey (USGS)
Earth Resources Observation and Science (EROS) Center
47914 252nd Street
Sioux Falls, SD 57198
Phone: 605-594-2527
gail.schmidt.ctr@usgs.gov

NOTICE:  This email may contain confidential, proprietary, or competition
sensitive bid or proposal procurement information.  Unauthorized disclosure
of this information may carry criminal penalties as set forth in the
Procurement Integrity Act, 41 U.S.C. 423, as amended.  Further, the
unauthorized disclosure of certain commercial information by civil servants
may result in fines or imprisonment under the Trade Secrets Act (18 U.S.C.
1905).  If you have received this information in error, please delete it,
including all copies, and notify the sender of the error immediately.

**Comment by gschmidt-usgs** [comment]
I pulled this scene down from EarthExplorer and ran it through
convert_lpgs_to_espa without any issues.

-----------------------------------------------------------------------------------------------------
Gail Schmidt
Software Engineer
Stinger Ghaffarian Technologies (SGT)
Contractor to the U.S. Geological Survey (USGS)
Earth Resources Observation and Science (EROS) Center
47914 252nd Street
Sioux Falls, SD 57198
Phone: 605-594-2527
gail.schmidt.ctr@usgs.gov

NOTICE:  This email may contain confidential, proprietary, or competition
sensitive bid or proposal procurement information.  Unauthorized disclosure
of this information may carry criminal penalties as set forth in the
Procurement Integrity Act, 41 U.S.C. 423, as amended.  Further, the
unauthorized disclosure of certain commercial information by civil servants
may result in fines or imprisonment under the Trade Secrets Act (18 U.S.C.
1905).  If you have received this information in error, please delete it,
including all copies, and notify the sender of the error immediately.

**Comment by Leonhalt3141** [comment]
It seems that my Docker environment does not work well...
I have tried other [Docker environment](https://github.com/CONABIO/LEDAPS/tree/master/ledaps_ls8l) and worked without any problems.

My Dockerfile is bellow. I could not recognize there is a problem installing tiff or geotiff library.

```
FROM ubuntu:16.04
ENV PYTHONUNBUFFERED 1

RUN mkdir /app
WORKDIR /app


RUN apt-get update -y && \
    apt-get install -y \
    #zlib1g zlib1g-dev \
    #libtiff5 libtiff5-dev libtiff-tools \
    #libgeotiff2 libgeotiff-dev \
    libxml2 libxml2-dev \
    g++ gfortran bison byacc flex csh make cmake \
    nano subversion git curl bison flex libjpeg-dev p7zip-full jbigkit-bin libjbig-dev build-essential python python-pip

RUN mkdir /usr/local/hdf4

RUN apt-get install -y libopenmpi-dev openmpi-bin

RUN wget http://tukaani.org/lzma/lzma-4.32.7.tar.gz && \
	tar xvfz lzma-4.32.7.tar.gz && cd lzma-4.32.7 && \
	./configure --prefix=/usr/local && \
	make -j2 && make insall & ldconfig

# Zlib
RUN curl http://zlib.net/zlib-1.2.11.tar.gz -O -L && \
	tar xvfz zlib-1.2.11.tar.gz  && cd zlib-1.2.11 && \
	./configure --prefix=/usr/local && \
	make -j2 && make install && ldconfig

# Proj4
RUN git clone https://github.com/OSGeo/proj.4.git && \
	cd proj.4/ && mkdir build && cd build && \
	cmake .. -DCMAKE_INSTALL_PREFIX=/usr/local && \
	make && make install

# Lib tiff
RUN curl ftp://download.osgeo.org/libtiff/tiff-4.0.7.tar.gz -O -L && \
	tar xvfz tiff-4.0.7.tar.gz && cd tiff-4.0.7 && \
	./configure --enable-cxx \
	--with-zlib-include-dir=/usr/local/include --with-zlib-lib-dir=/usr/local/lib \
	--with-jpeg-include-dir=/usr/include --with-jpeg-lib-dir=/usr/lib \
	#--with-lzma-include-dir=/usr/local/include --with-lzma-lib-dir=/usr/local/lib \
	--without-x  --disable-static --prefix=/usr/local && \
	make -j2 && make install && ldconfig

# Lib geotiff
RUN curl http://download.osgeo.org/geotiff/libgeotiff/libgeotiff-1.4.2.tar.gz -O -L && \
	tar xvfz libgeotiff-1.4.2.tar.gz && cd libgeotiff-1.4.2 && \
	./configure --with-proj=/usr/local --with-zlib --with-jpeg=/usr/local \
	--with-libtiff=/usr/ --prefix=/usr/local/ && \
	make -j3 && make install && ldconfig

# HDF4
RUN cd /usr/local/hdf4 && curl https://support.hdfgroup.org/ftp/HDF/releases/HDF4.2.12/src/hdf-4.2.12.tar -O && \
	tar xvf hdf-4.2.12.tar && \
	cd /usr/local/hdf4/hdf-4.2.12 && \
	./configure && make -j3 && make check && make install && ldconfig

RUN mkdir /usr/local/hdf-eos
RUN cd /usr/local/hdf-eos && curl ftp://edhs1.gsfc.nasa.gov/edhs/hdfeos/latest_release/HDF-EOS2.19v1.00.tar.Z -O && tar -xzvf HDF-EOS2.19v1.00.tar.Z
RUN cd /usr/local/hdf-eos/hdfeos && ./configure -enable-install-include CC=/usr/local/hdf4/hdf-4.2.12/hdf4/bin/h4cc && make -j3 && make install && ldconfig

RUN cd /app && curl https://support.hdfgroup.org/ftp/HDF5/current18/src/hdf5-1.8.18.tar -O && tar xvf hdf5-1.8.18.tar && cd hdf5-1.8.18 && ./configure --prefix=/usr/local/ && make -j3 && make install

# NetCDF4
RUN cd /app && curl ftp://ftp.unidata.ucar.edu/pub/netcdf/netcdf-4.4.1.1.tar.gz -O && tar xvfz netcdf-4.4.1.1.tar.gz && cd netcdf-4.4.1.1 && ./configure && make -j3 && make install && ldconfig

ENV HDFEOS_GCTPINC="/usr/local/hdf-eos/hdfeos/hdfeos2/include"
ENV HDFEOS_GCTPLIB="/usr/local/hdf-eos/hdfeos/hdfeos2/lib"
#ENV TIFFINC="/usr/include/x86_64-linux-gnu/"
#ENV TIFFLIB="/usr/lib/x86_64-linux-gnu/"
ENV TIFFINC="/usr/local/include/"
ENV TIFFLIB="/usr/local/lib/"
ENV GEOTIFF_INC="/usr/local/include/"
ENV GEOTIFF_LIB="/usr/local/lib/"
#ENV GEOTIFF_INC="/usr/include/geotiff/"
#ENV GEOTIFF_LIB="/usr/lib/"
ENV HDFINC="/usr/local/hdf4/hdf-4.2.12/hdf4/include/"
ENV HDFLIB="/usr/local/hdf4/hdf-4.2.12/hdf4/lib/"
ENV HDF5INC="/usr/local/include/"
ENV HDF5LIB="usr/local/lib/"
ENV HDFEOS_INC="/usr/local/hdf-eos/hdfeos/include/"
ENV HDFEOS_LIB="/usr/local/hdf-eos/hdfeos/hdfeos2/lib"
ENV JPEGINC="/usr/include/"
ENV JPEGLIB="/usr/lib/"
ENV XML2INC="/usr/include/libxml2/"
ENV XML2LIB="/usr/lib/x86_64-linux-gnu/"
ENV ZLIBINC="/usr/include/"
ENV ZLIBLIB="/usr/lib/x86_64-linux-gnu/"
ENV JBIGINC="/usr/include/"
ENV JBIGLIB="/usr/lib/"
ENV NCDF4INC="/usr/local/include"
ENV NCDF4LIB="/usr/local/lib"
ENV EXTRA_OPTIONS="$CFLAGS -I$INSTALL_DIR/include -L/usr/lib -lm"

RUN cd /usr/local/ && git clone https://github.com/USGS-EROS/espa-product-formatter.git espa-common
RUN mkdir -p /usr/local/espa-tools
ENV PREFIX="/usr/local/espa-tools/"


RUN cd /usr/local/espa-tools && mkdir static_data && cd static_data && curl http://edclpdsftp.cr.usgs.gov/downloads/auxiliaries//land_water_poly/land_no_buf.ply.gz -O -L && gunzip land_no_buf.ply.gz
ENV ESPA_LAND_MASS_POLYGON="$PREFIX/static_data/land_no_buf.ply"

ENV ESPAINC="/usr/local/espa-tools/include"
ENV ESPAINC="/usr/local/espa-common/raw_binary/format_conversion_libs/"
ENV ESPALIB="/usr/local/espa-tools/lib"
RUN ln -s /usr/local/espa-common/raw_binary/format_conversion_libs/*.h /usr/local/include/
RUN ln -s /usr/local/espa-common/raw_binary/io_libs/*.h /usr/local/include
RUN ln -s /usr/local/espa-common/raw_binary/common/*.h /usr/local/include
RUN cd /usr/local/espa-common/ && make install && ldconfig


#Surface reflectances...

RUN cd /usr/local && mkdir espa-surface && git clone https://github.com/USGS-EROS/espa-surface-reflectance.git espa-surface/


ENV BIN="/usr/local/espa-tools/bin/"
ENV PATH="/usr/local/espa-tools/bin/:$PATH"

RUN cd /usr/local/espa-surface/not-validated-prototype-lasrc/c_version/src && make -j3 && make install

RUN cp /usr/local/espa-surface/not-validated-prototype-lasrc/c_version/scripts/do_lasrc.py $BIN
RUN cp /usr/local/espa-surface/not-validated-prototype-lasrc/c_version/src/lasrc $BIN
RUN cd /usr/local/espa-surface/not-validated-prototype-lasrc/landsat_aux/src && make -j3 #&& make install
RUN cd /usr/local/espa-surface/not-validated-prototype-lasrc/landsat_aux/scripts && make -j3 #&& make install

RUN cp /usr/local/espa-surface/not-validated-prototype-lasrc/landsat_aux/src/combine_l8_aux_data $BIN

RUN cp /usr/local/espa-surface/not-validated-prototype-lasrc/landsat_aux/scripts/updatelads.py $BIN
```

**Comment by ronaldddilley** [comment]
You are not installing wget, but using it for the lzma install.  And it isn't failing the lzma build because of some typos in the lzma RUN command.

This should fix the RUN command, but you also need to add wget to the apt-get install.

RUN wget http://tukaani.org/lzma/lzma-4.32.7.tar.gz && \
	tar xvfz lzma-4.32.7.tar.gz && cd lzma-4.32.7 && \
	./configure --prefix=/usr/local && \
	make -j2 && make install && ldconfig

I'm still waiting for the build to finish, so haven't tired it yet.

**Comment by ronaldddilley** [comment]
convert_lpgs_to_espa works for me after the mentioned Dockerfile fixes
I didn't try it without the fixes.

**Comment by Leonhalt3141** [comment]
Thanks for your help.
My old version of Dockerfile included wget installation, so it did not relate to the issue.

Actually, I have launched a container from `docker-compose` and 'convert_lpgs_to_espa' has not worked well.
But once I launched a container by `docker run -it --name "lasrc_test" larsc:test /bin/bash`, 'convert_lpgs_to_espa' worked fine.

My `docker-compose.yaml` file is bellow.
Is this issue caused by a bug of docker-compose?

```
version: '2'
services:
  web:
    image: larsc:test
    build: .
    volumes:
      - .:/src
    ports:
      - "8000:8000"
```

**Comment by Leonhalt3141** [comment]
Also, LZMA library which I installed in Docker was not correct.

Right source:
https://github.com/kobolabs/liblzma

**Comment by gschmidt-usgs** [comment]
Thanks.  Hopefully things are working better for you now.

-----------------------------------------------------------------------------------------------------
Gail Schmidt
Software Engineer
Stinger Ghaffarian Technologies (SGT)
Contractor to the U.S. Geological Survey (USGS)
Earth Resources Observation and Science (EROS) Center
47914 252nd Street
Sioux Falls, SD 57198
Phone: 605-594-2527
gail.schmidt.ctr@usgs.gov

NOTICE:  This email may contain confidential, proprietary, or competition
sensitive bid or proposal procurement information.  Unauthorized disclosure
of this information may carry criminal penalties as set forth in the
Procurement Integrity Act, 41 U.S.C. 423, as amended.  Further, the
unauthorized disclosure of certain commercial information by civil servants
may result in fines or imprisonment under the Trade Secrets Act (18 U.S.C.
1905).  If you have received this information in error, please delete it,
including all copies, and notify the sender of the error immediately.

**Comment by Leonhalt3141** [comment]
I figured out more detail.
I have used API of [landsat-util](https://github.com/developmentseed/landsat-util) to download Landsat scenes.

When I downloaded each tiff file and mtl file to convert them by `convert_lpgs_to_espa`, I got error for `convert_lpgs_to_espa`.
But when I downloaded a tar.bz file and converted them, it works.

Thanks for your support.

**Comment by gschmidt-usgs** [comment]
Thanks for the information.

-----------------------------------------------------------------------------------------------------
Gail Schmidt
Software Engineer
Stinger Ghaffarian Technologies (SGT)
Contractor to the U.S. Geological Survey (USGS)
Earth Resources Observation and Science (EROS) Center
47914 252nd Street
Sioux Falls, SD 57198
Phone: 605-594-2527
gail.schmidt.ctr@usgs.gov

NOTICE:  This email may contain confidential, proprietary, or competition
sensitive bid or proposal procurement information.  Unauthorized disclosure
of this information may carry criminal penalties as set forth in the
Procurement Integrity Act, 41 U.S.C. 423, as amended.  Further, the
unauthorized disclosure of certain commercial information by civil servants
may result in fines or imprisonment under the Trade Secrets Act (18 U.S.C.
1905).  If you have received this information in error, please delete it,
including all copies, and notify the sender of the error immediately.

**Comment by cicerocasj** [comment]
@Leonhalt3141 
Ok, but, what's the difference between them?

**Comment by BrandonSmithJ** [comment]
For anyone else having this issue, the solution I found was to use gdalwarp to remove the tiling / compression:

`gdalwarp -co TILED=NO -co COMPRESS=DEFLATE old.tif new.tif`
