### ISSUE TITLE
where I can find the documentation of LaSRC?

### ISSUE THREAD

**Issue by suredream** [USGS-EROS/espa-surface-reflectance#81]
Not very sure.

**Comment by gschmidt-usgs** [comment]
Here is the article that was published by the algorithm's author:

http://www.sciencedirect.com/science/article/pii/S0034425716301572


-----------------------------------------------------------------------------------------------------
Gail Schmidt
Software Engineer
Stinger Ghaffarian Technologies (SGT)
Contractor to the U.S. Geological Survey (USGS)
Earth Resources Observation and Science (EROS) Center
47914 252nd Street
Sioux Falls, SD 57198
Phone: 605-594-2527
gail.schmidt.ctr@usgs.gov

NOTICE:  This email may contain confidential, proprietary, or competition
sensitive bid or proposal procurement information.  Unauthorized disclosure
of this information may carry criminal penalties as set forth in the
Procurement Integrity Act, 41 U.S.C. 423, as amended.  Further, the
unauthorized disclosure of certain commercial information by civil servants
may result in fines or imprisonment under the Trade Secrets Act (18 U.S.C.
1905).  If you have received this information in error, please delete it,
including all copies, and notify the sender of the error immediately.

**Comment by ronaldddilley** [comment]
Resolved
