### ISSUE TITLE
combine_l8_aux_data exitting with parse error

### ISSUE THREAD

**Issue by prag-nrsc** [USGS-EROS/espa-surface-reflectance#83]
I am having trouble generating the fused file from combine_l8_aux_data executable. I downloaded three modis CMA files which have moved to the public domain from ladsweb but all of them were detected with parse error.Could you please suggest a solution .

**Comment by prag-nrsc** [comment]
![parse_err_l8_aux](https://user-images.githubusercontent.com/22541373/26872946-e9f5b60e-4b95-11e7-9a69-85543553b030.png)

**Comment by yannforget** [comment]
Hi,

In my case it worked only with these products:

``` bash
#terra_cma
ladsweb.modaps.eosdis.nasa.gov/archive/allData/6/MOD09CMA/

#terra_cmg
ladsweb.modaps.eosdis.nasa.gov/archive/allData/6/MOD09CMG/

#aqua_cma
ladsweb.modaps.eosdis.nasa.gov/archive/allData/6/MYD09CMA/

#aqua_cmg
ladsweb.modaps.eosdis.nasa.gov/archive/allData/6/MYD09CMG/
```

**Comment by prag-nrsc** [comment]
Hello. Thank you for the alt. links.. shall try running the code with
downloaded datasets and post the feedback here..

**Comment by gschmidt-usgs** [comment]
The following is the LAADS URL and directories for pulling down the LAADS
data for the L8 auxiliary products.

SERVER_URL = 'ladsweb.modaps.eosdis.nasa.gov'
TERRA_CMA = '/allData/6/MOD09CMA/'
TERRA_CMG = '/allData/6/MOD09CMG/'
AQUA_CMA = '/allData/6/MYD09CMA/'
AQUA_CMG = '/allData/6/MYD09CMG/'

-----------------------------------------------------------------------------------------------------
Gail Schmidt
Software Engineer
Stinger Ghaffarian Technologies (SGT)
Contractor to the U.S. Geological Survey (USGS)
Earth Resources Observation and Science (EROS) Center
47914 252nd Street
Sioux Falls, SD 57198
Phone: 605-594-2527
gail.schmidt.ctr@usgs.gov

NOTICE:  This email may contain confidential, proprietary, or competition
sensitive bid or proposal procurement information.  Unauthorized disclosure
of this information may carry criminal penalties as set forth in the
Procurement Integrity Act, 41 U.S.C. 423, as amended.  Further, the
unauthorized disclosure of certain commercial information by civil servants
may result in fines or imprisonment under the Trade Secrets Act (18 U.S.C.
1905).  If you have received this information in error, please delete it,
including all copies, and notify the sender of the error immediately.

**Comment by prag-nrsc** [comment]
Hi.I downloaded all required  files but faced same error .I traced it to
SDstart() returning -1. Is it that I installed hdf4 incorrectly? What is
this HDFLIBAPI which is appended before  SDstart() in various include
(.h)files?

**Comment by prag-nrsc** [comment]
Hi. Like I mentioned before , the combine_l8_aux_data is failing for
certain files. I ran a small program to perform the first check using i.e
SDstart(filename,DFACC_READ) and it returned a positive value while for
certain files esp. MYD09CMG it is returning -1 and read is failing. What
should I do to solve the problem. Pl suggest.

**Comment by gschmidt-usgs** [comment]
We are using HDF version 4.2.5.  Is combine_l8_aux_data failing for all files or just certain ones?  If just certain files, can you please provide information on which files are failing?

**Comment by prag-nrsc** [comment]
Hi..Tried running the script on random files..
Year  2017 -  failed for Julian days 108 , 137 , 168  ; *passed *for Julian
day 49 .
Year 2016  - failed for 362 , 343 ; *passed* for 331 , 335

I used hdf-4.2.10 (without_netcdf flag turned on) during build.
My bash profile has HDFINC , HDFLIB , NCDF4INC , NCDF4LIB defined.

**Comment by gschmidt-usgs** [comment]
I will take a look at this in a few days when I complete a couple of other priority items.

**Comment by prag-nrsc** [comment]
Ok sure...

**Comment by prag-nrsc** [comment]
Hello. Small suggestion.

If the "*EXE name*" in the Makefile of the src folder could be changed to
suit software version changes , it would be appreciated .

For example -  "*combine_l8_aux_data_2.7.0"* instead of generic "
*combine_l8_aux_data*" as EXE name  would be useful in knowing OLD Vs NEW
exe.

Thanks & Regards.

**Comment by gschmidt-usgs** [comment]
Users are welcome to change the Makefile to meet their needs, such as adding the version number to the executable name.

**Comment by gschmidt-usgs** [comment]
We have been able to process the Julian days which you indicated earlier had failed (2017 - 108, 137, 168; 2016 - 362, 343).  It is a bit odd that the software is working ok for you on some of the HDF files and not others.  Are you able to view the failed HDF files in a visualization package such as ENVI or HDFView to make sure the download is valid?

**Comment by prag-nrsc** [comment]
Did that.Thank you.

**Comment by prag-nrsc** [comment]
Hello.
I had performed the check before. The error thrown by HDFView is attached
for reference. So is it a download issue?

**Comment by gschmidt-usgs** [comment]
If HDFView cannot read the file, then there is a problem with your HDF files.  It is very likely a download issue, as we are able to process all the HDF files you indicated were a problem.

**Comment by prag-nrsc** [comment]
Hmmn. Ok Sir,shall download once more and confirm.
Thank you once again for your patience.

**Comment by prag-nrsc** [comment]
Hello Sir.Yes indeed it was a download issue.
Thank you for the corrective suggestion.
Shall be in touch ..
