### ISSUE TITLE
metadata_api.py xml_filename error

### ISSUE THREAD

**Issue by pamgnicba** [USGS-EROS/espa-surface-reflectance#89]
metadata_api.py (called by lndsrbm.py in the get_metadata function) fails with error:

"raise MetadataError('Must provide an xml_filename if no environment'
MetadataError: Must provide an xml_filename if no environment variables are defined (XML_SCHEMA, ESPA_SCHEMA, ARD_SCHEMA) so that an XSD Schema can be loaded"

I do not understand why metadata_api.py does not find the xml_filename, which has been found by all the previous processes under lndsrbm.py

**Comment by gschmidt-usgs** [comment]
I believe this error message actually refers to the schema location/name
versus the actual XML file.  The schema is needed to validate the input XML
filename.

-----------------------------------------------------------------------------------------------------
Gail Schmidt
Software Engineer
Stinger Ghaffarian Technologies (SGT)
Contractor to the U.S. Geological Survey (USGS)
Earth Resources Observation and Science (EROS) Center
47914 252nd Street
Sioux Falls, SD 57198
Phone: 605-594-2527
gail.schmidt.ctr@usgs.gov

NOTICE:  This email may contain confidential, proprietary, or competition
sensitive bid or proposal procurement information.  Unauthorized disclosure
of this information may carry criminal penalties as set forth in the
Procurement Integrity Act, 41 U.S.C. 423, as amended.  Further, the
unauthorized disclosure of certain commercial information by civil servants
may result in fines or imprisonment under the Trade Secrets Act (18 U.S.C.
1905).  If you have received this information in error, please delete it,
including all copies, and notify the sender of the error immediately.

**Comment by gschmidt-usgs** [comment]
It does look like metadata_api.py can be called with the input XML file so
that the location of the schema can be parsed from the input XML.  However,
the calling lndsrbm.py script is not sending in the XML file.  Line 329 in
lndsrbm.py could be modified to pass in the xml_filename to the Metadata
class.  We will test that out as part of our next release and see if it
works properly.

-----------------------------------------------------------------------------------------------------
Gail Schmidt
Software Engineer
Stinger Ghaffarian Technologies (SGT)
Contractor to the U.S. Geological Survey (USGS)
Earth Resources Observation and Science (EROS) Center
47914 252nd Street
Sioux Falls, SD 57198
Phone: 605-594-2527
gail.schmidt.ctr@usgs.gov

NOTICE:  This email may contain confidential, proprietary, or competition
sensitive bid or proposal procurement information.  Unauthorized disclosure
of this information may carry criminal penalties as set forth in the
Procurement Integrity Act, 41 U.S.C. 423, as amended.  Further, the
unauthorized disclosure of certain commercial information by civil servants
may result in fines or imprisonment under the Trade Secrets Act (18 U.S.C.
1905).  If you have received this information in error, please delete it,
including all copies, and notify the sender of the error immediately.

**Comment by gschmidt-usgs** [comment]
One additional note, this lndsrbm code is only used for pre-Collections
data.  It is quite possible/likely that our support of pre-Collections will
be pulled from this source code in future releases.

-----------------------------------------------------------------------------------------------------
Gail Schmidt
Software Engineer
Stinger Ghaffarian Technologies (SGT)
Contractor to the U.S. Geological Survey (USGS)
Earth Resources Observation and Science (EROS) Center
47914 252nd Street
Sioux Falls, SD 57198
Phone: 605-594-2527
gail.schmidt.ctr@usgs.gov

NOTICE:  This email may contain confidential, proprietary, or competition
sensitive bid or proposal procurement information.  Unauthorized disclosure
of this information may carry criminal penalties as set forth in the
Procurement Integrity Act, 41 U.S.C. 423, as amended.  Further, the
unauthorized disclosure of certain commercial information by civil servants
may result in fines or imprisonment under the Trade Secrets Act (18 U.S.C.
1905).  If you have received this information in error, please delete it,
including all copies, and notify the sender of the error immediately.

**Comment by pamgnicba** [comment]
I have modified the lndsrbm.py script from espa_metadata = Metadata() to espa_metadata = Metadata(xml_filename) and it seems working.

Thank you very much.
