### ISSUE TITLE
Inconsistency between SR ordered from ESPA and processed with the LaSRC code in master branch

### ISSUE THREAD

**Issue by Woodstonelee** [USGS-EROS/espa-surface-reflectance#90]
Hi all, I deployed the master branch of espa-surface-reflectance on our local server and successfully finished atmospheric correction of a Landsat-8 TOA scene with its product ID: LC08_L1TP_018030_20150822_20170225_01_T1. Our in-house generated SR looks reasonable except when I compare it with the same scene of SR ordered from ESPA website. Each pixel values are somewhat different. Generally, the generated SR from the master branch of this repo are slightly lower than the one ESPA order. I'm worried that the version of atmospheric correction code in this master branch is over-correcting. Is the master branch here in line with the production code used to generate SR data on ESPA order website? 

We need to process about 10k scenes at the moment and cannot wait that long to order SR from ESPA. Thus it'd make more sense for us to do the atmospheric correction in house at the moment and not to put too much stress on the ESPA server. But it'd be much better if our generated SR from the code here match exactly with the ESPA order. 

Thanks a lot, 

Zhan.

**Comment by ronaldddilley** [comment]
Thanks for trying out the LaSRC code!  We're glad to hear from you.  Could we bother you to provide some additional information before we investigate this issue?  Please check the xml file for the SR you generated through ESPA for LC08_L1TP_018030_20150822_20170225_01_T1 to verify that it was produced with the same LaSRC version as the master.  Alternatively, perhaps you could repeat the LC08_L1TP_018030_20150822_20170225_01_T1 order to make sure you have a product from the most recent code.

Also, ESPA performance has not been an issue lately, so we would expect that a 10K scene order would complete easily within a day or two and you would not need to process it yourself.

**Comment by Woodstonelee** [comment]
Thanks a lot, Ronald! It was the different LaSRC version. My ESPA order was from 1.2.1! I reordered the scene from the ESPA. And now my in-house processed SR is the same with the ESPA, and now they are both from LaSRC 1.3.1!  Thanks again for the prompt comment!
