### ISSUE TITLE
LaSRC not generating Pixel QA (quality assessment) properly

### ISSUE THREAD

**Issue by ntsack47** [USGS-EROS/espa-surface-reflectance#96]
I'm new to this but when I run LaSRC it won't give me pixel_qa band as indicated in user guides (e.g. LSDS-1368_ L8_Surface-Reflectance-Code-LASRC-Product-Guide). And I couldn't find an option when running do_lasrc.py to generate one... The files I'm trying to process are LC08_L1TP ( sometimes L1GT), and other results are generated (and converted to geotiff) correctly (e.g. Lasrc_sr_band1.tif). I think files ordered from USGS today still has pixel_qa.

**Comment by gschmidt-usgs** [comment]
pixel_qa is not generated by the LaSRC code.  It is generated by the
pixel_qa code in https://github.com/USGS-EROS/espa-l2qa-tools.
